# Generated by Django 3.2.4 on 2021-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuscarRaças',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('podeserferoz', models.CharField(max_length=20)),
                ('tamanho', models.CharField(max_length=20)),
                ('inteligencia', models.CharField(max_length=20)),
            ],
        ),
    ]
