# Generated by Django 3.2.6 on 2021-08-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buscarraças',
            old_name='podeserferoz',
            new_name='espetativa_de_vida',
        ),
        migrations.RenameField(
            model_name='buscarraças',
            old_name='nome',
            new_name='nome_raça',
        ),
    ]
