# Generated by Django 3.2.6 on 2021-08-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscar', '0002_auto_20210828_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buscarraças',
            old_name='espetativa_de_vida',
            new_name='expectativa_de_vida',
        ),
    ]
